[package]
name = "fsdb"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
reflink-copy = "=0.1.27"
uuid = { version = "1.0", features = ["v4", "fast-rng"] }

[dev-dependencies]
rand = "0.8"